# H2データベース設定（これだけでメモリ上に自動生成されます）
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2コンソールを有効にする（ブラウザでDBの中身を見れます）
spring.h2.console.enabled=true

# MyBatis設定
mybatis.mapper-locations=classpath:sample/app/dao/mapper/*.xml